export const APP_CONFIG = {
  name: 'GUNUCO',
  productName: 'GUNUCO Admin',
  tagline: 'Production house operations',
  defaultLocationId: 'loc_production',
  locationName: 'GUNUCO Production House',
  city: 'Vijayawada',
  currency: 'INR',
  locale: 'en-IN',
  timezone: 'Asia/Kolkata',
  taxRate: 0.05,
  mockLatencyMs: 700,
  weddingMinHours: 72,
  weddingMaxHours: 720,
  occasionMaxDays: 30,
  branchFeatureEnabled: false,
  globalPosEnabled: true,
  deliveryBands: [
    { fromKm: 0, toKm: 5, fee: 0, label: 'Up to 5 km' },
    { fromKm: 5, toKm: 8, fee: 39, label: 'Over 5 to 8 km' },
    { fromKm: 8, toKm: 10, fee: 59, label: 'Over 8 to 10 km' },
    { fromKm: 10, toKm: 15, fee: 159, label: 'Over 10 to 15 km' },
  ],
  maxDoorstepKm: 15,
  customCakeDeliveryExempt: true,
  supportSubdomain: 'support',
} as const;
